/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default']
    IEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IEpDataBoard: typeof import('~icons/ep/data-board')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFiles: typeof import('~icons/ep/files')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpRight: typeof import('~icons/ep/right')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
