name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/ci.yml"

jobs:
  build-check:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # 只执行类型检查，不进行完整构建
      - name: Type Check
        run: vue-tsc --noEmit
        continue-on-error: true  # 即使类型检查失败也继续执行

      # 只构建前端部分，不打包 Electron 应用
      - name: Build Frontend
        run: vite build
        continue-on-error: true  # 即使构建失败也继续执行