name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/ci.yml"

jobs:
  lint-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
        continue-on-error: true  # 即使lint失败也继续执行

      - name: Type Check
        run: npm run typecheck
        continue-on-error: true  # 即使类型检查失败也继续执行

      - name: Build
        run: npm run build:web  # 只构建Web部分，速度更快