name: Release

on:
  push:
    tags:
      - 'v*'  # 推送标签时触发，如 v1.0.0

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist_electron/*.exe
            dist_electron/*.zip
          draft: true  # 创建草稿版本，需要手动发布
          generate_release_notes: true  # 自动生成发布说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 